In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder
import numpy as np

train = pd.read_csv("HW2_hr-analytics_train.csv")
train = train.fillna(0)

test = pd.read_csv("HW2_hr-analytics_test.csv")

train = pd.get_dummies(train, columns=['sales', 'salary'])

X_train = train.drop('left', axis=1)
y_train = train['left']

weights = np.ones(X_train.shape[1])     # 創weight和X_train同
weights[2] = 2                          # 第三個特徵加權2
X_train_weighted = X_train * weights    # 調整X加權

# Create a Decision Tree Classifier
model = DecisionTreeClassifier()

model.fit(X_train_weighted, y_train)

test = pd.get_dummies(test, columns=['sales', 'salary'])
X_test_weighted = test * weights    # 調整y加權

y_pred = model.predict(X_test_weighted)
y_pred_train = model.predict(X_train)

test['left'] = y_pred
df_filepath = 'HW2_hr-analytics_test_sol.csv'
df = pd.DataFrame({'left': test['left']})
df.to_csv('HW2_hr-analytics_test_sol.csv', index=False)

confusion = confusion_matrix(y_train, y_pred_train)
print("混淆矩陣:\n", confusion)

In [10]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix

feature=['satisfaction_level','last_evaluation','number_project','average_montly_hours','time_spend_company','Work_accident','promotion_last_5years']   # remove 'sales', and 'salary'

train = pd.read_csv("HW2_hr-analytics_train.csv")
train = train.fillna(0)
train = pd.get_dummies(train, columns=['sales', 'salary'])

for column in train.columns:
    # append 'salery_low', 'salery_medium', 'salery_high' to feature
    if 'salary' in column:
        feature.append(column)

    # append 'sales_sales', 'sales_account', 'sales_hr', ... to feature
    elif 'sales' in column:
        feature.append(column)

test = pd.read_csv("HW2_hr-analytics_test.csv")
test = pd.get_dummies(test, columns=['sales', 'salary'])

for i in range(len(feature)):
    for j in range(1,len(feature)-1):
        if j>i:
            X_train = train[[feature[i],feature[j]]]
            y_train = train['left']
            model = DecisionTreeClassifier()
            model.fit(X_train, y_train)

            X_test = test[[feature[i],feature[j]]]
            y_pred = model.predict(X_test)
            y_pred_train = model.predict(X_train)
            confusion = confusion_matrix(y_train, y_pred_train)
            print("混淆矩陣:",feature[i],feature[j],"\n", confusion)

混淆矩陣: satisfaction_level last_evaluation 
 [[7388  220]
 [ 291 2101]]
混淆矩陣: satisfaction_level number_project 
 [[7422  186]
 [ 614 1778]]
混淆矩陣: satisfaction_level average_montly_hours 
 [[7475  133]
 [ 200 2192]]
混淆矩陣: satisfaction_level time_spend_company 
 [[7380  228]
 [ 189 2203]]
混淆矩陣: satisfaction_level Work_accident 
 [[7339  269]
 [ 777 1615]]
混淆矩陣: satisfaction_level promotion_last_5years 
 [[7312  296]
 [ 754 1638]]
混淆矩陣: satisfaction_level sales_IT 
 [[7306  302]
 [ 753 1639]]
混淆矩陣: satisfaction_level sales_RandD 
 [[7310  298]
 [ 753 1639]]
混淆矩陣: satisfaction_level sales_accounting 
 [[7306  302]
 [ 754 1638]]
混淆矩陣: satisfaction_level sales_hr 
 [[7305  303]
 [ 753 1639]]
混淆矩陣: satisfaction_level sales_management 
 [[7314  294]
 [ 760 1632]]
混淆矩陣: satisfaction_level sales_marketing 
 [[7306  302]
 [ 755 1637]]
混淆矩陣: satisfaction_level sales_product_mng 
 [[7302  306]
 [ 748 1644]]
混淆矩陣: satisfaction_level sales_sales 
 [[7304  304]
 [ 753 1639]]
混淆矩陣: satisfaction_level sa

藉由以上結果可得知只取satisfaction_level和average_montly_hours這兩項特徵時，預測出的結果準確率較高。

進一步推測對於員工在職期間最重視的是工時和對公司的滿意度，為員工離職與否的優先考量。